# https://github.com/pre-commit/pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    #-   id: check-shebang-scripts-are-executable
    -   id: check-json
    -   id: check-yaml
    -   id: check-toml
    #-   id: check-check-xml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: detect-private-key

  - repo: local
    hooks:
      - id: lint-py  # currently a test, not to be enforced yet
        name: Lint (py)
        language: system
        entry: ruff check
        #files: ^src/
        #files: *.py
        types: [python]
      - id: ruff-format-check  # currently a test, not to be enforced yet
        name: ruff-format-check (py)
        language: system
        entry: ruff format --check
        #files: ^src/
        #files: *.py
        types: [python]
      - id: ruff-format-fix  # currently a test, not to be enforced yet
        name: ruff-format-check (py)
        stages: [pre-push]
        language: system
        entry: ruff format
        #files: ^src/
        #files: *.py
        types: [python]
